version: "3.3"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgresql-local
    volumes:
      - "/home/myuser/docker-apps/volumes/postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: root
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin2020
    depends_on:
      - db
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/hubco
    ports:
      - "3001:3001"
    depends_on:
      - db