default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'root' %>
  database: <%= ENV['DATABASE_NAME'] || 'myexp_development' %>
  pool: <%= ENV['DATABASE_CONNECTION_POOL'] || 10 %>

development:
  <<: *default

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: emam_test
